In [3]:
import numpy as np

In [4]:
array1 = np.arange(6)
array1

array([0, 1, 2, 3, 4, 5])

In [4]:
array1.reshape((1, 3, 2))

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [5]:
array1.reshape((2, 3, 1))

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [27]:
ar1

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
ar1 = array1.reshape(2, 3)

In [29]:
ar1[[0, 1], 0:2]

array([[0, 1],
       [3, 4]])

In [10]:
array1.reshape((6, 1, 1))

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [11]:
array1.reshape((2, 1, 3))

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [5]:
ar = array1.reshape((3, 1, 2))

In [6]:
ar

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [7]:
ar.T

array([[[0, 2, 4]],

       [[1, 3, 5]]])

In [19]:
ar[2, 0, 1]

5

In [31]:
ar[[0, 2], 0, 0:2]

array([[0, 1],
       [4, 5]])

In [33]:
name = np.array(['John', 'Mike', 'Minjun', 'Mimie'])

In [34]:
name

array(['John', 'Mike', 'Minjun', 'Mimie'], dtype='<U6')

In [37]:
name[[1,0,2,3]]

array(['Mike', 'John', 'Minjun', 'Mimie'], dtype='<U6')

In [8]:
import pandas as pd
dict = {'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict = pd.DataFrame(dict)

In [12]:
df_dict.to_dict()

{'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 22}, 'col3': {0: 3, 1: 33}}